sequentech/iam

authapi/api/tests.py
authapi/api/views.py
authapi/authmethods/m_pwd.py
authapi/authmethods/tests.py
authapi/authmethods/utils.py
authapi/captcha/tests.py
authapi/captcha/views.py
authapi/utils.py

The system of error is similar as agora_elections

Changed system of error.

---

.travis.yml
authapi/api/__init__.py
authapi/api/fixtures/initial.json
authapi/api/urls.py
authapi/authapi/settings.py
authapi/authapi/urls.py
authapi/authmethods/m_dnie.py
authapi/authmethods/m_email.py
authapi/authmethods/m_pwd.py
authapi/authmethods/m_sms.py
authapi/captcha/urls.py
authapi/utils.py
requirements.txt
runtests.sh

Django 1.9 was released yesterday. I've fixed some bugs and removed deprecation warnings for django 1.10.

Updated to django1.9 removing django1.10 deprecation

---

authapi/api/test_data.py
authapi/api/tests.py
authapi/authmethods/m_email.py

Reference PR in agora-gui-admin: agoravoting/agora-gui-admin#21

Fix spaces email

---

README.md
authapi/api/fixtures/initial.json
authapi/api/fixtures/saas.json
authapi/api/test_data.py
authapi/api/tests.py
authapi/api/views.py
authapi/authapi/settings.py
authapi/authmethods/m_email.py
authapi/authmethods/m_sms.py
authapi/authmethods/tests.py
authapi/captcha/tests.py
authapi/utils.py
runtests.sh

See https://trello.com/c/PEVzd3jH/504-use-replaces-for-replacing-url-s-and-code-s-instead-of-being-a-template-because-it-s-too-powerful-and-for-example-the-char-makes for details

Send code templates fix

---

authapi/api/tasks.py
authapi/api/test_data.py
authapi/api/tests.py
authapi/api/urls.py
authapi/api/views.py
authapi/authmethods/m_email.py
authapi/captcha/urls.py
authapi/utils.py

Reference PR in agora-gui-admin: https://github.com/agoravoting/agora-gui-admin/pull/21

Fixed spaces in email when add new census.

---

authapi/api/test_data.py
authapi/api/tests.py

This patch adds unittests for autofill extra_field

Unit test for autofill census extra_field

---

requirements.txt

This patch updates some dependencies to fix security vulnerabilities
detected by github dependant bot.

requirements: fix security vulnerabilities

---

authapi/api/management/commands/send_report.py
authapi/api/tests.py
authapi/authmethods/m_email_otp.py
authapi/authmethods/m_sms_otp.py
authapi/authmethods/utils.py
authapi/utils.py

sometimes we were comparing naive dates without timezone information with dates that had timezone, so we're fixing that now.

not using naive timezone-less datetimes anymore

---

authapi/api/management/commands/send_report.py
authapi/api/models.py

Improving custom PDF Reports by allowing to count not only votes, also active voters and other custom variables.

Improve Custom PDF Reports

---

.github/workflows/python.yml
authapi/api/tests.py
authapi/utils.py

* fixing khmac
* allowing separators in hmac token userid and adding some test cases
* fix unit test import reference
* making tests work again

Fix khmac: allowing separators in userids and adding some test cases

---

authapi/api/views.py

When an admin user has permissions only to a children election, it was not being shown in the election list in admin ui. (#188)

Children election listing

---

authapi/api/management/commands/bulk_insert_voters.py

The following changes have been applied to the administrative command
bulk_insert_voters:
- Make it work with parent-children elections
- Use the ';' separator and document that no escape character can be
used
- Document briefly in the code how it works with some example CSV

Make bulk_insert_voters work with parent elections

---

dependabot.yml

Adding a dependabot.yml file so that it tracks security issues in currently maintained version-branches.

adding dependabot.yml

---

.github/dependabot.yml
.github/dependabot.yml.tpl

Enable dependabot security updates only for now.

Disable dependabot version updates

---

iam/api/management/commands/upsert_users.py

This is a follow-up [on a previous fix](https://github.com/sequentech/iam/pull/225) on the upsert users script. The part that updates users still had bug.

Fix updating upsert users

---

.github/workflows/ort.yml
.github/workflows/python.yml
requirements.txt

Include changes to master from [this PR.](https://github.com/sequentech/iam/pull/231)

Security update (6.1.x)

---

iam/api/tasks.py
iam/api/test_data.py
iam/api/tests.py
iam/api/views.py

Include changes from [this PR](https://github.com/sequentech/iam/pull/235) in version 7.0.x

Support sending reminders to voters who didn't cast a vote

---

iam/api/views.py

Fixes #270
When creating elections with specific ids, the id automatic sequence number (`api_authevent_id_seq`  in postgresql) is not updated. This means that when creating an election with no specific id, it might fail.
When creating elections with specific ids, the the id automatic sequence number (`api_authevent_id_seq`  in postgresql) should be updated to the `max(api_authevent_id_seq, biggest(authevent.id))`.

Creating elections with specific ids should update `api_authevent_id_seq`

---

iam/utils.py

Parent issue: https://github.com/sequentech/meta/issues/77

Fix alternative method auth message links

---

iam/utils.py

Parent issue: https://github.com/sequentech/meta/issues/77

Fix alternative method auth message links (#284)

---

iam/api/models.py
iam/authmethods/m_dnie.py
iam/authmethods/m_email.py
iam/authmethods/m_email_otp.py
iam/authmethods/m_emailpwd.py
iam/authmethods/m_openidconnect.py
iam/authmethods/m_pwd.py
iam/authmethods/m_smart_link.py
iam/authmethods/m_sms.py
iam/authmethods/m_sms_otp.py
iam/utils.py

Parent issue: https://github.com/sequentech/meta/issues/122

✨ Multilingualism

---

iam/api/models.py
iam/authmethods/tests.py

Parent issue: https://github.com/sequentech/meta/issues/142

🐞 Can't send email-otp

---

iam/api/tasks.py
iam/api/urls.py
iam/api/views.py
iam/iam/settings.py
iam/iam/test_settings.py

Parent issue: https://github.com/sequentech/meta/issues/146

✨ Enable progressive tallies

---

requirements.txt

Parent issue: https://github.com/sequentech/meta/issues/230

Security updates (#303)

---

iam/api/models.py
iam/authmethods/m_dnie.py
iam/authmethods/m_email.py
iam/authmethods/m_email_otp.py
iam/authmethods/m_emailpwd.py
iam/authmethods/m_openidconnect.py
iam/authmethods/m_pwd.py
iam/authmethods/m_smart_link.py
iam/authmethods/m_sms.py
iam/authmethods/m_sms_otp.py
iam/utils.py

Parent issue: https://github.com/sequentech/meta/issues/122

✨ Multilingualism (#295)

---

iam/api/views.py

Parent issue: https://github.com/sequentech/meta/issues/127

✨ Role-based login for election manager

---

iam/api/tests.py

Parent issue: https://github.com/sequentech/meta/issues/260

Fix unit tests

---

iam/api/tests.py
iam/api/views.py

Parent issue: https://github.com/sequentech/meta/issues/265

🐞 Login allowed with election closed

---

iam/api/tests.py
iam/api/views.py

Parent issue: https://github.com/sequentech/meta/issues/265

🐞 Login allowed with election closed (#311)

---

iam/api/models.py

Parent issue: https://github.com/sequentech/meta/issues/274

Can't start election on v10

---

iam/api/models.py

Parent issue: https://github.com/sequentech/meta/issues/274

Can't start election on v10 (#316)

---

iam/api/models.py

Parent issue: https://github.com/sequentech/meta/issues/268

🐞 election-title_i18n is not applied everywhere

---

iam/api/models.py

Parent issue: https://github.com/sequentech/meta/issues/268

🐞 election-title_i18n is not applied everywhere (#318)

---

requirements.txt

Parent issue: https://github.com/sequentech/meta/issues/279
Fixes:
- https://github.com/sequentech/iam/security/dependabot/35
- https://github.com/sequentech/iam/security/dependabot/34
- https://github.com/sequentech/iam/security/dependabot/33

Security updates (#321)

---

iam/api/management/commands/bulk_delete_voters.py
iam/api/tasks.py
iam/api/views.py
iam/captcha/views.py
iam/utils.py

Parent issue: https://github.com/sequentech/meta/issues/284

🐞 Sending census auth codes is not done in async manner

---

requirements.txt

Parent issue: https://github.com/sequentech/meta/issues/339

🛡 Security updates

---

requirements.txt

Parent issue: https://github.com/sequentech/meta/issues/339

🛡 Security updates (#328)

---

requirements.txt

Parent issue: sequentech/meta#567
Dependabot tickets:
- https://github.com/sequentech/iam/security/dependabot/38
- https://github.com/sequentech/iam/security/dependabot/39

Security dependencies update

---

requirements.txt

Parent issue: sequentech/meta#567
Dependabot tickets:
- https://github.com/sequentech/iam/security/dependabot/38
- https://github.com/sequentech/iam/security/dependabot/39

Security dependencies update (#330)

---

iam/api/models.py
iam/api/urls.py
iam/api/views.py

Parent issue: https://github.com/sequentech/meta/issues/206

✨ Election turnout overview / graph for election managers

---

iam/api/models.py
iam/api/urls.py
iam/api/views.py

Parent issue: https://github.com/sequentech/meta/issues/206

✨ Election turnout overview / graph for election managers (#334)

---

iam/api/tasks.py

Parent issue: https://github.com/sequentech/epi/issues/36

✨ Check if the authorities are online (#335)

---

iam/authmethods/m_openidconnect.py
requirements.txt

Parent issue: https://github.com/sequentech/meta/issues/716

🐞 OIDC: Use Authorization Code Flow instead of implicit flow

---

iam/api/tasks.py

Parent issue: https://github.com/sequentech/meta/issues/402

🐞 Trustees struggle to respond to director

---

iam/api/tasks.py

Parent issue: https://github.com/sequentech/meta/issues/402

🐞 Trustees struggle to respond to director (#332)

---

requirements.txt

Parent issue: https://github.com/sequentech/meta/issues/810

🛡 Security updates (#342)

---

iam/api/views.py

Parent issue: https://github.com/sequentech/meta/issues/209

✨ Download election turnout

---

iam/api/views.py

Parent issue: https://github.com/sequentech/meta/issues/209

✨ Download election turnout (#344)

---

iam/utils.py

Parent issue: https://github.com/sequentech/meta/issues/1095

🐞 Increase default pagination size

---

iam/utils.py

Parent issue: https://github.com/sequentech/meta/issues/1095

🐞 Increase default pagination size (#346)

---

iam/api/urls.py
iam/api/views.py
iam/iam/settings.py
iam/iam/test_settings.py

Parent issue: https://github.com/sequentech/meta/issues/752

✨🐞 Improve/rethink/fix Live Preview

---

iam/api/views.py

Parent issue: https://github.com/sequentech/meta/issues/205

✨ Increase the timeout due to user activity 

---

iam/api/urls.py
iam/api/views.py
iam/iam/settings.py
iam/iam/test_settings.py

Parent issue: https://github.com/sequentech/meta/issues/752

✨🐞 Improve/rethink/fix Live Preview (#348)

---

iam/api/views.py

Parent issue: https://github.com/sequentech/meta/issues/205

✨ Increase the timeout due to user activity  (#349)

---

iam/api/views.py

Parent issue: https://github.com/sequentech/meta/issues/1009

🐞 Archive parent/child elections
