- authapi/authmethods/tests.py
- authapi/authmethods/utils.py
This patch convert emails to punycode[1] before validation so we'll
allow emails with tilde.
The email is stored as string and python supports unicode, so the only
part modified is the validation.
[1] https://en.wikipedia.org/wiki/Punycode
> Allow emails with tilde

- authapi/api/models.py
- authapi/api/views.py
Previously, census query (used during census download in the admin UI) was not ordered by default. This meant that it by default the paging mechanism might not work well, because each page is done with a query that returns randomly ordered results. This resulted in the correct number of records, but some records were missing and some records were duplicated.
We solve it by sorting by default by increasing user_id. We also improve the census filter query to use QuerySet.extra(where="..") instead of having a full raw sql subquery and brute-force "user_id in <result from subquery>", which required bigger raw_sql duplicating the base census query. This probably makes filtering census queries more efficient/faster too.
> stabilizing paged census query

- authapi/authmethods/m_email.py
- authapi/authmethods/m_email_otp.py
- authapi/authmethods/m_sms.py
- authapi/authmethods/m_sms_otp.py
- authapi/authmethods/utils.py
A bug was introduced during code refatoring. Authentication methods that are not using OTP time-limited tokens were (bug) applying time-limits of the authentication code as if they were an OTP code. Fixing that.
> fix timeout of non-otp authentication methods

- requirements.txt
The addition of all the implicit dependencies of authapi to the `requirements.txt` file (which happened in PR https://github.com/agoravoting/authapi/pull/171 ) has raised that urllib3 is also a dependency that requires an update. This set of PRs will fix that.
> Bump urllib3 from 1.25.11 to 1.26.8

- authapi/api/views.py
When an admin user has permissions only to a children election, it was not being shown in the election list in admin ui.
> Children election listing

- authapi/api/management/commands/bulk_insert_voters.py
The following changes have been applied to the administrative command
bulk_insert_voters:
- Make it work with parent-children elections
- Use the ';' separator and document that no escape character can be
used
- Document briefly in the code how it works with some example CSV
> Make bulk_insert_voters work with parent elections

- iam/api/fixtures/saas.json
- iam/authmethods/m_emailpwd.py
- iam/authmethods/utils.py
the refactor on explicit authentication made it redundant some code and a previous fix didn't account for that.
> fixing setting users email in `edit_user` function 

- iam/authmethods/utils.py
As emails are case insensitive per the standard, the following
changes are applied in login, registration, etc:
- email extra fields will be queried in a case-insesitive manner
- received email extra fields will be canonized into lower-case
> make email fields case insensitive

- authapi/authmethods/m_emailpwd.py
In `email-and-password` the verification if a voter has voted too many times was being done twice:
1. once using the new general function for it `verify_num_successful_logins`, which is the correct way.
2. another time using the old code that verified this, that didn't work for parent-children elections.
In this commit we solve this simply by removing the code for 2.
> fixing authentication second time for parent-children elections

- iam/api/management/commands/upsert_users.py
A recent change in the code introduced a bug for upserting users through the `config.yml`. This PR fixes the call to create the users by using the spread operator to pass the parameters.
> Fix upsert users

- iam/api/management/commands/upsert_users.py
This is a mirror PR for version 6.1.x that was included on master on [this PR](https://github.com/sequentech/iam/pull/226). This is a follow-up [on a previous fix](https://github.com/sequentech/iam/pull/225) on the upsert users script. The part that updates users still had bug.
> Fix updating upsert users (6.1.x)

- iam/api/tasks.py
- iam/api/urls.py
- iam/api/views.py
Creating a task that can set the public candidates for an election and
all the children elections, and logs this in the activity log.
> adding set-public-candidates support

- iam/api/test_data.py
- iam/api/tests.py
- iam/api/views.py
- iam/authmethods/m_email.py
- iam/authmethods/m_email_otp.py
- iam/authmethods/m_sms.py
- iam/authmethods/m_sms_otp.py
- iam/contracts/base.py
- iam/iam/settings.py
- iam/iam/test_settings.py
- iam/utils.py
* Add an extra field `html_message` to the auth-event config, next to the [`msg` field](https://sequentech.github.io/documentation/docs/general/reference/election-creation-json#census-config-msg), along with corresponding unit tests. If html_message is empty or null, then it's not used.
* Add an extra field `html_message` to the IAM CensusSendAuth view, next to the `msg` field, along with corresponding unit tests.
* Add an IAM settings field `ALLOW_HTML_EMAILS` to enable this feature.
* Fix issue when creating an election that could modify an auth method settings.
* Add an `optional` field to contracts.
> Support HTML format when sending email auth-codes

- iam/api/models.py
- iam/api/tasks.py
- iam/api/test_data.py
- iam/api/tests.py
- iam/api/views.py
Enable sending emails/sms messages to part of the census, filtering by whether the voters have already casted their vote or not.
* Add optional `filter` parameter to `send_auth` api call, when sending messages to the whole census. Valid filter values are ´voted´and ´not_voted´.
* Add tests for elections with email and sms authentication methods.
> Support sending reminders to voters who didn't cast a vote

- iam/api/management/commands/show_pdf.py
- iam/api/views.py
the show_pdf will be in `auth_method_config['config']` and not in a `auth_method_config`.
> bugfix: show pdf not working as expected

- iam/api/tests.py
- iam/utils.py
For elections using the `fixed-code` feature, trying to send the first authentication message would fail if no code was already present. This fixes it and modifies the test to check it works.
> Fix bug on fixed-codes

- iam/api/urls.py
- iam/api/views.py
Automate filling in election IDs. If the election ID in the Election JSON is negative, replace it with new Election IDs.
* Add endpoint that returns the highest existing election ID.
> Election IDs automation

- iam/api/urls.py
- iam/api/views.py
Automate filling in election IDs. If the election ID in the Election JSON is negative, replace it with new Election IDs.
* Add endpoint that returns the highest existing election ID.
> Election IDs automation (#259)

- iam/api/test_data.py
- iam/api/tests.py
- iam/authmethods/utils.py
Parent tracking issue: https://github.com/sequentech/meta/issues/61
Allow to configure a parameterized/templated url in the go-to-url after a voter logins, where one of the possible template variables is the list of children election ids in which the voter can vote.
Right now there's an (undocumented) manner to let a voter know that they are part of the census and their credentials work without yet allowing them to vote: the `go-to-url` url in iam's `authentication-action`. However, the website in that url doesn't get any information about the voter attributes, and EPI wants to show in which children elections the voter can vote.
> adding support for giving away information about children election info through URL params in go-to-url

- iam/api/test_data.py
- iam/api/tests.py
- iam/authmethods/utils.py
Parent tracking issue: https://github.com/sequentech/meta/issues/61
Allow to configure a parameterized/templated url in the go-to-url after a voter logins, where one of the possible template variables is the list of children election ids in which the voter can vote.
Right now there's an (undocumented) manner to let a voter know that they are part of the census and their credentials work without yet allowing them to vote: the `go-to-url` url in iam's `authentication-action`. However, the website in that url doesn't get any information about the voter attributes, and EPI wants to show in which children elections the voter can vote.
> adding support for giving away information about children election info through URL params in go-to-url 

- .github/workflows/ort.yml
Parent issue: https://github.com/sequentech/meta/issues/59
Use the reusable workflow from the meta repository instead.
> Fix ORT Github Workflow (#275)

- iam/authmethods/utils.py
Parent issue: https://github.com/sequentech/meta/issues/76
Within an election with email authentication method and a `phone` telephone extra field, when importing users from the admin console, the phone number never gets imported, and instead appears empty.
Should import telephone just fine.
> 🐞 Error importing users, phone number empty (#281)

- iam/api/tasks.py
Parent issue: https://github.com/sequentech/meta/issues/115
- Current Behavior
With a set of parent-children elections and having many children (100 for example), if allow-tally is clicked in the parent, then the parent election is allowed before the children. Therefore, tally can be launched when some children are still not tallyable, and this can create errors.
- Expected Behavior
Parent election should be the last to be allowed to tally in parent-children elections: when it is allowed to tally, all its children should have also been allowed to tally already.
> Race condition in parent-children election between allow-tally and tally

- iam/api/tests.py
- iam/api/views.py
Parent issue: https://github.com/sequentech/meta/issues/260
Ensuring resend-auth-codes REST API works when alternative auth method id is supplied
> 🐞 Resend auth codes in email-otl or sms-otp doesn't work in alt-auth-method (#307)

- iam/authmethods/m_email_otp.py
- iam/authmethods/m_sms_otp.py
- iam/authmethods/utils.py
- iam/utils.py
Parent issue: https://github.com/sequentech/meta/issues/260
System was sending the wrong message (from the main auth_method instead of from the alt_auth_method because send_code was not given the proper auth_method config.
> Fix send_codes for alt auth methods

- iam/api/management/commands/bulk_delete_voters.py
- iam/api/tasks.py
- iam/api/views.py
- iam/captcha/views.py
- iam/utils.py
Parent issue: https://github.com/sequentech/meta/issues/284
> 🐞 Sending census auth codes is not done in async manner (#323)

- iam/api/tasks.py
Parent issue: https://github.com/sequentech/epi/issues/36
> ✨ Check if the authorities are online

- iam/api/views.py
Parent issue: https://github.com/sequentech/meta/issues/1009
> 🐞 Archive parent/child elections (#356)
